= Get sizes of arbitrary types at compile time
:hp-tags: c++

The more I work with c++ and template programming in particular, the more I love it. No, seriously - we have a language inside another language which allows us to create beautiful constructs. One of my recent problems was the finding of types sizes. I.e. I have a number of types, say `char, float, double` and I need to get their sizes and place them in a vector. The number of types can be different and in any combination. That sounds like a work for http://en.cppreference.com/w/cpp/language/parameter_pack[variadic templates]. Using templates allow us to write generic code that will work the same on all platforms.

I like to write code that requires several steps in back order or from outside. Let me show this on example. Since in the end I need to query the size and put the value into the container the last function will look this:

[source,cpp]
----
template<typename T>
void assignImpl(vector<int>& v)
{
	v.push_back(sizeof(T));
}
----

Very simple and straightforward.


[source,cpp]
----
template<typename T>
void assignImpl(vector<int>& v)
{
	v.push_back(sizeof(T));
}

template <typename... Args>
void assign(vector<int>& v)
{
	vector<int> temp{(assignImpl<Args>(v), 0)...};
	(void)temp;
}

template<typename... Args>
vector<int> calcSize()
{
	vector<int> v;
	assign<Args...>(v);

	return v;
}
----