= Call a function from the string name and arguments
:hp-tags: c++

Recently I had an interesting task - a cheat system. All the system should do is to call functions during apllication (in my case - a game) run through a console command (game console). Functions can accept different number of arguments. In simple words the system should be able to call a function

[source,c]
----
bool foo(int, float);
----

with a console command
----
foo 42 10.5
----
I'll not describe how I'm receiving this string as well how I'm parsing it, but at some point I'm operating with a vector of strings where the first element - the name of the function, like this
----
{ "foo", "42", "10.5" }
----
Having this I need somehow call a correct function and pass a correct number of parameters with a correct type.

There's no way to call an unknown function knowing only a name. At least I don't know such a way. So in order to call something I need first register it. I have a wrapper class `Cheat` for my function and a helper function to create an instance:
[source,c]
----
template<typename ...Args>
std::shared_ptr<CheatBase> makeCheat(void(*funcPtr)(Args... arguments))
{
	return std::make_shared<Cheat<Args...>>(funcPtr);
}
----