= Vulkan by example. Lesson 0.
:hp-tags: c++, vulkan

Hi everybody. Today we'll talk about Vulkan - the modern api for communication with gpu device. There're already some information with tutorials on the web as well as books so why another one. I'll try to explain - these tutorials out there are great by all means, but personally for me they are hard to follow. In this series I'll try to build a mental picture around the api, I'll try not to just follow instructions and create some structures because they say I need this, but I'll try to understand why I need this. For that I'll use pictures, a lot of pictures. And if you read https://nikitablack.github.io/2017/03/23/Functional-programming-in-c-by-example.html[one of my previous posts] you know that I'm a fan of functional approach and I'll use this approach through tutorials. I'll build every next lesson on top of the other adding a new stuff, but not modifying it - I found it easyer to follow (though sometimes I'll have to tweak the old code to make it work with the new, but I'll try to minimize this).

So let's start. What should we do? Of course render a tesselated teapot! I did it before with https://nikitablack.github.io/2016/07/23/Direct-X-12-by-example.html[DirectX 12], so I know a little how to do it. It covers a lot of pipeline stages so I have to touch different parts of the api, which is good. It's almost complete application, not just triangle or static mesh. This would be our goal:

