= Vulkan by example. Lesson 0.
:hp-tags: c++, vulkan

Hi everybody. Today we’ll talk about Vulkan - the modern API for communication with GPU device. There's already some information and tutorials on the web as well as books so why another one. I’ll try to explain - these tutorials out there are great by all means, but personally, for me, they are hard to follow. In this series I’ll try to build a mental picture around the API, I’ll try not to just follow instructions and create some structures because somebody says I need this, but I’ll try to understand why I need this. For that, I’ll use pictures, a lot of them. And if you read https://nikitablack.github.io/2017/03/23/Functional-programming-in-c-by-example.html[one of my previous posts] you know that I’m a fan of functional approach and I’ll use this approach through tutorials. I’ll build every next lesson on top of the previous adding a new stuff, but not modifying it - I found it easier to follow (though sometimes I’ll have to return back and tweak the old code to make it work with the new, but I’ll try to minimize this).

===== Disclaimer
I'm not an expert guru ninja, I'm just learning. And definitely, there will be mistakes in my lessons. I'm kindly asking you to point to them so I can correct it soon. You can do it via comments here, or Reddit, where I'm planning to leave a link, or cpp slack Vulkan channel which I check quite often (and which is very silent btw).

===== The goal
So let's start. What should I do? Of course, render a tesselated teapot! I did it before with https://nikitablack.github.io/2016/07/23/Direct-X-12-by-example.html[DirectX 12], so I already know from which side to approach. It covers a lot of pipeline stages so I have to touch different parts of the API, which is good. It's almost a complete application, not just a triangle or static mesh. This would be our goal:

video::8RCWeKLlVew[youtube, width=640, height=360]

Amazing, isn't it? Sorry for the blurriness - youtube mercilessly fucked up the quality and I don't know how to achieve true HD picture.

Ok, I know I want to see a rotating teapot and the very first thing I need is a data.

===== The data