= Vulkan by example 2 - Resources
:hp-tags: c++, vulkan

Last time I promised we'll start to create Vulkan resources (and the name of the article suggests that) but before we need to do one very important thing. In https://TODO[prevoius] tutorial we created a couple of objects but we never destroyed them. For every _create_ function the Vulkan have a corresponding _destroy_ function, for every _allocate_ - _free_. So we need to call some in the end of our application. The problem is that we can have a lot of objects and it's may be difficult to track what is active and what is not. Thankfully the Vulkan have a mechanism for tracking live objects with the help of validation layers. These are the special software layer that is injected between a Vulkan function call and a driver call and which can do some checks. The layers are very important during the development, I'd say it's a must have for every application but should be turned off for the release build (but still there's a way to activate them even on a finished product. Yes, you can start your favorite Steam game with the Vulkan support and see all the calls with the information layer turned on!). So let's activate them. 

===== Validation layers

There're multiple types of layers, but we'll use only one - `VK_LAYER_LUNARG_standard_validation`. Actually this is not a single layer, but a special meta-definition for a serie of layers which will be loaded during the application run. For now we're interesten in object traking layer, but later we'll use the core validation and maybe some others. https://vulkan.lunarg.com/doc/view/1.0.13.0/windows/layers.html[Here] you can find more information about layers as well as a setup for different platforms.

I added a compilation directive `ENABLE_VULKAN_DEBUG_UTILS` which can be tuned in a https://github.com/nikitablack/vulkan_by_example_2/blob/lesson_2/src/teapot/CMakeLists.txt#L59[CMakeLists.txt]. If this variable is defined I'll do some debug-related stuff. For example, TODO[add the layer name to the list]. Later this list is used during the TODO[instance creation].

NOTE: `VkDeviceCreateInfo` which is used for the logical device creation have a field `ppEnabledLayerNames` field. Previously there was a differentioation between instance and device layers (similar to extensions) but now device layers are obsolete and should not be used.

Debug utils.
Debug callback.
Show the output example on exit.

===== Vertex buffer

Create the buffer.
Upload data.

===== Index buffer

Create the buffer.

